language: ruby
rvm:
  - rvm 2.1.1
  - rvm 2.1.5
  - rvm 2.2.0
  - rvm 2.2.1
  - rvm 2.2.2

install:
  - bundle

before_script:
  - RAILS_ENV=test rake db:create db:migrate

env:
  global:
    - TWILIO_ACCOUNT_SID=TWILIOACCOUNTSID0000
    - TWILIO_AUTH_TOKEN=TWILIOAUTHTOKEN0000
    - TWILIO_PHONE_NUMBER=TWILIOPHONENUMBER0000
